final humanReadableAbi = [
  "function createVestingSchedule(address _beneficiary, uint256 _start, uint256 _cliff, uint256 _duration, uint256 _slicePeriodSeconds, bool _revocable, uint256 _amount)",
  "constructor(address token_)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "function release(bytes32 vestingScheduleId, uint256 amount)",
  "event Released(uint256 amount)",
  "function renounceOwnership()",
  "function revoke(bytes32 vestingScheduleId)",
  "event Revoked()",
  "function transferOwnership(address newOwner)",
  "function withdraw(uint256 amount)",
  "function computeNextVestingScheduleIdForHolder(address holder) view returns (bytes32)",
  "function computeReleasableAmount(bytes32 vestingScheduleId) view returns (uint256)",
  "function computeVestingScheduleIdForAddressAndIndex(address holder, uint256 index) pure returns (bytes32)",
  "function getLastVestingScheduleForHolder(address holder) view returns (tuple(bool initialized, address beneficiary, uint256 cliff, uint256 start, uint256 duration, uint256 slicePeriodSeconds, bool revocable, uint256 amountTotal, uint256 released, bool revoked))",
  "function getToken() view returns (address)",
  "function getVestingIdAtIndex(uint256 index) view returns (bytes32)",
  "function getVestingSchedule(bytes32 vestingScheduleId) view returns (tuple(bool initialized, address beneficiary, uint256 cliff, uint256 start, uint256 duration, uint256 slicePeriodSeconds, bool revocable, uint256 amountTotal, uint256 released, bool revoked))",
  "function getVestingScheduleByAddressAndIndex(address holder, uint256 index) view returns (tuple(bool initialized, address beneficiary, uint256 cliff, uint256 start, uint256 duration, uint256 slicePeriodSeconds, bool revocable, uint256 amountTotal, uint256 released, bool revoked))",
  "function getVestingSchedulesCount() view returns (uint256)",
  "function getVestingSchedulesCountByBeneficiary(address _beneficiary) view returns (uint256)",
  "function getVestingSchedulesTotalAmount() view returns (uint256)",
  "function getWithdrawableAmount() view returns (uint256)",
  "function owner() view returns (address)"
];
